REGEX_EMAIL = '^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$'

COOKIE_SECRET = "K!?V98mB2uJ}&8"

MAX_LENGHT_USER_NAME = 20
MAX_LENGHT_USER_FIRST_NAME = 20
MAX_LENGHT_USER_LAST_NAME = 50
MAX_LENGHT_USER_EMAIL = 100
MAX_LENGHT_USER_PASSWORD = 50
MIN_LENGHT_USER_PASSWORD = 10
MAX_LENGHT_TWEET_TEXT = 280
MAX_LENGHT_IMAGE_PATH = 100
REGEX_USER_ID = "^[0-9]*$"